### ISSUE TITLE
Pandas requirement

### ISSUE THREAD

**Issue by sandervm** [dominiktraxl/pykrakenapi#1]
Hi there,

Tried to run the help:
from pykrakenapi import KrakenAPI
help(KrakenAPI)

But this gave an error `ImportError: No module named 'pandas'`

Easily resolved this by installing pandas: `pip install pandas`, but maybe an idea to add this to the package requirements itself or mention in the README that it is required to be present?

**Comment by dominiktraxl** [comment]
Thanks! I added pandas to the setup.py and also mentioned it in the readme now.
