### ISSUE TITLE
'EGeneral:Invalid arguments:ordertype' error with some order types

### ISSUE THREAD

**Issue by SB0gmail** [dominiktraxl/pykrakenapi#12]
Versions
OS:  Windows 10
Python:   3
krakenex: 
I am able to achieve market and limit orders with code:
myorder = k.add_standard_order(pair = tradepair,type = 'sell',ordertype = 'market',volume = buylots, price = myprice)

But when I try to put a stop loss or trailing stop order with equivalent code:
myorder = k.add_standard_order(pair = tradepair,type = 'sell',ordertype = 'trailing-stop',volume = buylots, price = myprice)

I get an error "KrakenAPIError: ['EGeneral:Invalid arguments:ordertype']"
Please help.

**Comment by t-mortimer** [comment]
It looks like Kraken has re-enabled the stop loss order type as of the 20th Feb. See here [(https://blog.kraken.com/post/1494/kraken-enables-advanced-orders-and-adds-10-currency-pairs/)]

Maybe worth giving it another try now.

**Comment by dominiktraxl** [comment]
Do you still get the error, @SB0gmail?
