### ISSUE TITLE
Add standard order

### ISSUE THREAD

**Issue by iq** [dominiktraxl/pykrakenapi#14]
Having issues placing an order on Kraken.

My code:
`buyOrder = k.add_standard_order(pair="XXRPXXBT", type="buy", ordertype="market", volume="31", price = "0.00009160")
print(buyOrder)

orders = k.get_open_orders()
print(orders)`

There's no orders getting placed, and no errors messages.

**Comment by trys10** [comment]
Hi iq, for the order to actually get placed on Kraken you need to add the argument 
validate = False
Good luck.
