### ISSUE TITLE
add_standard_order() is not working

### ISSUE THREAD

**Issue by carsonpo** [dominiktraxl/pykrakenapi#17]
Here's the code: 

```
buy = k.add_standard_order("XXBTZUSD", "buy", "market", 0.002)

print(buy)
```

And when run, it prints  `{'descr': {'order': 'buy 0.00200000 XBTUSD @ market'}}`

However, my account never reflects that I'm submitting an order at all. My API key has all permissions.

Is there something I'm doing wrong?

**Comment by trystanmortimer** [comment]
Hi carsonpo, for the order to actually get placed on Kraken you need to add the argument 

validate = False

Good luck.
