### ISSUE TITLE
Public calls and private calls should be counted separately

### ISSUE THREAD

**Issue by pietrosperoni** [dominiktraxl/pykrakenapi#22]
According to
https://support.kraken.com/hc/en-us/articles/206548367-What-is-the-API-call-rate-limit- 
there are two different counters. One works for public calls and is IP based, and basically you cannot make more than one request a second. A second counter is for private calls and is a more complicated function explained there. At least this was my understanding. I have actually wrote a bot that had two threads, one that would ping kraken once per second to get the public values. And then in another thread I would be threading. So I am quite confident that I am correct.

This is important because this is sensibly more than if you count public calls [and](url) private calls within the same limit. It also makes sense, as couinting them together would mean that a better programmer would simply call the public calls from a different IP and have an edge over more normal programmers.

All this to say that we should not count together public and private calls.

**Comment by dominiktraxl** [comment]
Thank you for the information! It seems that they have changed the call rate limit system recently. Would you be willing to implement the changes? Unfortunately, I won't be able to do this myself in the next few weeks.

**Comment by pietrosperoni** [comment]
Hmm, thanks for the invitation. My python is nowhere near your level, but I might give it a shot. I will let you know if/when I start. So if I haven't started, and you want to start at least we don't do double work.

**Comment by gonmator** [comment]
I think I can give a try to implement different counter for public and private API. My idea is to use `query_type='public'` in `callratelimiter` decorator to select that counter.

**Comment by dominiktraxl** [comment]
Thanks @gonmator for solving this!
