### ISSUE TITLE
Key error in get_recent_trades.

### ISSUE THREAD

**Issue by AlnsV** [dominiktraxl/pykrakenapi#23]
`
trades = pd.DataFrame(res['result'][pair])
KeyError: 'USDTUSD'`
The key actually is USDTZUSD. So the approach to get this working is adding '-' between base and quote.
So the pair should be 'USDT-USD' then the function queries the API using the string replace with '-' by '' and the key to dictionary would be the replace of '-' with 'Z'

**Comment by AlnsV** [comment]
Proposal: 
with pair being '<base>-<quote>' instead of '<base><quote>'
and data dictionary now declared in a explicit way
`# create data dictionary
        data = {
            'pair': pair.replace('-', ''),
            'since': since,
            'ascending': ascending
        }


        # query
        res = self.api.query_public('Trades', data=data)

        # check for error
        if len(res['error']) > 0:
            raise KrakenAPIError(res['error'])

        # create dataframe
        trades = pd.DataFrame(res['result'][pair.replace('-', 'Z')])
        # last timestamp
        last = int(res['result']['last'])`

**Comment by dominiktraxl** [comment]
Is there any reason you don't just query by 'USDTZUSD':
`trades, last = k.get_recent_trades('USDTZUSD')`
?

**Comment by dominiktraxl** [comment]
closing this.
