### ISSUE TITLE
['EAPI:Invalid signature']

### ISSUE THREAD

**Issue by TheHaricover** [dominiktraxl/pykrakenapi#24]
Hi,

I suppose this issue is linked to #22 but as I don't really know, I post a new issue.

So, using krakenex works well for the signature but as I pass the API to pykrakenapi, the signature becomes invalid.

My code is really simple, so the issue should be raising for anyone. If not, just tell me and I will check what's not working with my PC.

Thank you for your work !

**Comment by dominiktraxl** [comment]
Could you please provide a minimal example to reproduce the error? Don't paste your private keys, I'll test with my own ;)

**Comment by TheHaricover** [comment]
Ofc !

```
import krakenex
from pykrakenapi import KrakenAPI

krakenkey = "kraken.key"
api = krakenex.API()
api.load_key(krakenkey)
k = KrakenAPI(api)
print(k.get_account_balance("661766"))
```

**Comment by dominiktraxl** [comment]
Are you actually using a two-factor password (otp)? 
I'm not, and it's working as expected (e.g., your last call without any argument works: k.get_account_balance()).

**Comment by TheHaricover** [comment]
To connect to my account only.
Okay, I'll run some tests around the OTP.
Thanks !

**Comment by TheHaricover** [comment]
Okay ! It seems that the OTP was raising the error. So I guess the program doesn't need and OTP to connect to my account and do its things.
Thank you 😄
