### ISSUE TITLE
OHLC prices aren't the real ones

### ISSUE THREAD

**Issue by TheHaricover** [dominiktraxl/pykrakenapi#25]
Hi !

When I get a OHLC data frame, the prices aren't the same as showed on kraken, or on tradingview (which seems to be the same on both).

```
api = krakenex.API()
krakenkey = "kraken.key"
api.load_key(krakenkey)
k = KrakenAPI(api)
ohlc, last = k.get_ohlc_data("BCHUSD", 15)
print("ohlc :", ohlc)
```

If I compare the prices, they aren't the same.

**Comment by Ayoub000** [comment]
Hi,

You should probably check the timezone you're using to monitor prices in TradingView or Kraken because pykrakenapi seems to use Kraken's unixtime which is as i much as i saw is UTC.

**Comment by TheHaricover** [comment]
Hi,

I think you're right indeed. I had a lot of issues with time working on this. I think I might still have some xD
