### ISSUE TITLE
get_ohlc-data doesn't raise the good error

### ISSUE THREAD

**Issue by TheHaricover** [dominiktraxl/pykrakenapi#27]
Hi !

Shouldn't `get_ohlc_data` raise a `CallRateLimitError` instead of the `EAPI:Rate limit exceeded` of Krakenex ?

**Comment by dominiktraxl** [comment]
Yes, it should. Only if you had set the argument `tier=0` (in KrakenAPI), you should have been able to trigger  `EAPI:Rate limit exceeded`. I hope the recent changes with regards to the call rate limiter  solved that problem.
