### ISSUE TITLE
get_account_balance() error

### ISSUE THREAD

**Issue by syntax-co** [dominiktraxl/pykrakenapi#29]
get_account_balance() is returning a result 

pi\pykrakenapi.py", line 825, in get_account_balance
    balance = pd.DataFrame(index=['vol'], data=res['result']).T
KeyError: 'result'

**Comment by gonmator** [comment]
It seems that there was an error in the call to the Kraken API and the "result" key was not returned and, at the same time, the "error" array was also empty. That response seems to be not consistent with the documented Kraken API.

**Comment by dominiktraxl** [comment]
As this seems to be not related to pykrakenapi, I'm gonna close this.
