### ISSUE TITLE
Orders not beeing executed

### ISSUE THREAD

**Issue by mans17** [dominiktraxl/pykrakenapi#3]
Hi,

I'm trying to execute an order, with add_standard_order.

I know, it's written that it is untested, that's also why I test it =), here are my results : 
when used with validate=True, it works (when Kraken is online ^^) 

And when I put validate=False, I expect the order to be created, but it never seems to happen : I get the exact same result when validate is set to True. No order is created on Kraken, and I get the same output from the API (when I should expect something like a TXID ?)

here is the code : 
```
res =  k.add_standard_order(pair=string_pair, type="buy", ordertype="limit", volume=string_vol, price=string_price, userref=42, validate=False)
print (res)
```
Output : 

`{'descr': {'order': 'buy 300.00000000 XLMXBT @ limit 0.00001021'}}
`

Looking at your code, you seem : 
- not to want to "hammer" orders with "@callratelimiter" that is a good idea to avoid having several orders put at once =)
- not to force my input to validate=True, that was my first idea since the result is quite the same.

=> from what I see, I have to "blame" Kraken on this issue. Did I miss something ?

**Comment by mans17** [comment]
Problem solved !
The opposite of "validate=True" is "Validate=None".

Well, then, I tested limit orders with validate=None, and my first API order has been placed \o/

**Comment by dominiktraxl** [comment]
Thanks for the test! I added code to convert validate=False to validate=None.
