### ISSUE TITLE
Call rate limiter incomprehension

### ISSUE THREAD

**Issue by TheHaricover** [dominiktraxl/pykrakenapi#36]
Hi !

I noticed something with the call rate limiter.
If I put "None" for the tier, when I create the API, I got this error if I make too much calls :
```attempt: 000 | ['EAPI:Rate limit exceeded']```
But if I put "Intermediate" or even "Starter" I have the exact same error.
The error also happens with "Pro".

My account is "Intermediate"

What's happening ?

Edit : I saw [here](https://support.kraken.com/hc/en-us/articles/206548367-What-is-the-API-call-rate-limit-) that the Counter Decrease per second is 0.5. Would that be because of that ? (That doesn't explain the same error in "Starter" though). This implementation uses the Rest API, right ?

Edit : I found that ```['EAPI:Rate limit exceeded']``` is an error coming from the API itself. I thought it was coming from your implementation. That means that the implementation + my code are too fast for the API (as I also have a counter implemented in my side) ?

Edit : Alright. I found that the errors come from public calls and not private ones. So it means that my implementation of a public counter stinks. I don't know if your implementation have one so I'll work on it on my side. I think we can close this issue.

**Comment by dominiktraxl** [comment]
The call rate limiter of pykrakenapi acts on both private and public calls.
