### ISSUE TITLE
get_ticker_information

### ISSUE THREAD

**Issue by miwahn** [dominiktraxl/pykrakenapi#40]
Hi. Thanks for the great work on this. 
There might be a little problem with the get_ticker_information function - it's taking a list of tickers as an input, but  only seems to return a single row in the output dataframe. 
Sorry in advance if I missed/misunderstood anything

**Comment by dominiktraxl** [comment]
Hi. `get_ticker_information` takes a string as input, not a list (see docstring). So this works:
```
import krakenex
import pykrakenapi
k = pykrakenapi.KrakenAPI(krakenex.API())
k.get_ticker_information('AAVEETH,ZEURZUSD')
```
whereas
```k.get_ticker_information(['AAVEETH', 'ZEURZUSD'])```
doesn't throw an exception, but rather returns only the ticker information of the last entry of the list
