### ISSUE TITLE
get_account_balance() not working.

### ISSUE THREAD

**Issue by danwatson16** [dominiktraxl/pykrakenapi#41]
![3c6e1dfaa43608f5fe1144b91a199536](https://user-images.githubusercontent.com/53444082/102228215-5be1fc80-3ee2-11eb-92e5-d6864a443a48.png)
[](https://gyazo.com/3c6e1dfaa43608f5fe1144b91a199536)

**Comment by dominiktraxl** [comment]
Works without a problem on my setup. Did you resolve the problem in the meantime?

**Comment by tsferro2** [comment]
I am completely new to this/was wondering if either of you might be able to offer assistance...
for example, when I run:

`KrakenAPI(api).get_account_balance()
`
where api is my private key or public key, it throws:

`AttributeError: 'str' object has no attribute 'query_private'`
 
any pointers would be much appreciated, and thanks for the useful library

**Comment by mans17** [comment]
``$ /usr/bin/python3``
Python 3.9.2 (default, Feb 20 2021, 18:40:11)

>>> import krakenex
>>> from pykrakenapi import KrakenAPI
>>> api = krakenex.API()
>>> api.load_key("YOUR_KEY_IN_A_FILE_HERE")
>>> k = KrakenAPI(api)
>>> bal = k.get_account_balance()
>>> print (bal)

**Comment by dominiktraxl** [comment]
The issue seems to be resolved thanks to @mans17, please reopen if I'm mistaken.
