### ISSUE TITLE
add_standard_order

### ISSUE THREAD

**Issue by Guceri** [dominiktraxl/pykrakenapi#44]
I am trying to test out the order functionality and I am not able to get an order to generate.  There are no errors that come up, and the response is only the 'descr' dictionary of the order details.  

I tried typing in the incorrect symbol and I got an error back
I tired typing an incorrect order type and I got an error back
I tried typing an incorrect side (buy/sell) and got an error back
I tried using a volume value smaller than the threshold and got an error back
I tried to test cancel an order, and that worked.

for whatever reason, if I put a very large value for volume, I do NOT get an error back. 

I have tried all sorts of combinations to get this to work and think I have run out of ideas.  Any help would be appreciated.

the exact code used:
`order = k.add_standard_order(pair='ETHUSD', type='sell', ordertype='limit', volume=".02", price='1400.00')`

**Comment by mans17** [comment]
Have you tried to read documentation, such as https://github.com/dominiktraxl/pykrakenapi/issues/32 ?

**Comment by Guceri** [comment]
I did not look at closed issues, only the notes within the code. appreciate the response.

**Comment by mans17** [comment]
Validate is a kraken's API feature (not a pykrakenapi "specific feature") : https://www.kraken.com/features/api#private-user-trading

I also think that "validate=True" as default makes sure people do not exec wrong orders when testing (although pretty much EVERYONE gets into your problem)

Maybe would it be a good thing to add a FAQ in readme.md with "why is my order not being executed"

**Comment by Guceri** [comment]
It's never a bad idea to have a FAQ.
That initial walk through of any package when you first download them can be overwhelming as you are not entirely sure where to look for what.  I always find FAQ's and "quick start guides" are the most helpful to get up and running  and avoid "Gotcha's".
