### ISSUE TITLE
add_standard_order : Post Only 

### ISSUE THREAD

**Issue by Guceri** [dominiktraxl/pykrakenapi#46]
I am trying to add a post only setting for limit orders and seem to be having trouble finding the right syntax.  Thee is no example in the code and kraken's api docs don't show anything either.

The post only setting should be in the form of  a comma-delimited list in the `oflags` parameter.    I can not seem to get that to work.  Any thoughts?

**Comment by tsferro2** [comment]
I would also benefit from some more code examples

**Comment by Guceri** [comment]
`oflags='post''
