### ISSUE TITLE
Does this API work on Kraken demo ? 

### ISSUE THREAD

**Issue by Samuel-Bachorik** [dominiktraxl/pykrakenapi#49]
Hi i want to ask you if this API work also here - https://demo-futures.kraken.com
Because we are getting this error

`raise KrakenAPIError(res['error'])
pykrakenapi.pykrakenapi.KrakenAPIError: ['EAPI:Invalid key']`

**Comment by adm-github** [comment]
Short: it doesn't work.
pykrakenapi is based on krakenex which is using api.kraken.com and doesn't support the test account on demo-futures.kraken.com
