### ISSUE TITLE
Add support for 2-Factor Auth

### ISSUE THREAD

**Issue by nareddyt** [dominiktraxl/pykrakenapi#5]
Currently, it looks like a lot of functions accept the argument `otp`, but this argument is never used in the underlying logic. This means that these API calls fail if a user has 2FA enabled for the API. Turning off 2FA fixes the issue, but it's a security risk!

I think that fixing this would be easy. Everytime we call `self.api.query_private`, we could pass in the `otp` in the `data` argument (the calls currently leave this out because it defaults to `None`). This fits in with the [API documentation from Kraken](https://www.kraken.com/help/api), take a look at the POST data box. If you look at the underlying `krakenex` library, you'll see they do keep the nonce in the `data` object as described in the API docs. So if we pass the `otp` in there as well, it would store the data perfectly for signing.

However, this would also require a change on the `krakenex` side. If you take a look at the `_sign` method [here](https://github.com/veox/python3-krakenex/blob/master/krakenex/api.py#L204), they only use the `nonce` to sign. It would be very simple to also add the `otp` to sign it, pretty sure it would just be a string concat.

Let me know what you think. I haven't mentioned this to the `krakenex` community, but I can test it locally if you would like.

**Comment by dominiktraxl** [comment]
The `otp` argument gets passed to `self.api.query_private` through the `data` argument if it is set to anything other than `None`. It should work as expected, no need to change anything. 
If you do find that it is not working, I'll reopen the issue!
