### ISSUE TITLE
Cancel open order doesn't work

### ISSUE THREAD

**Issue by adm-github** [dominiktraxl/pykrakenapi#54]
https://github.com/dominiktraxl/pykrakenapi/blob/7cd45b5ab9b1f5f80b8e8b12f030879dcb936d4a/pykrakenapi/pykrakenapi.py#L1992

cancel_open_oder( ) accepts a txid (supposedly "transaction id"?) but when tested with real orders, krakenex raises ['EOrder:Invalid order']

The problem and issue resolution belongs to Krakenex (see https://github.com/veox/python3-krakenex/issues/85)

Until that's solved, this function won't work either.

**Comment by jonnymaserati** [comment]
Works okay for me?

Are you using the full `txid` (I think 20 characters excluding dashes) and is it a `str`?
