### ISSUE TITLE
 getting KrakenAPIError: ['EAPI:Invalid nonce'] w/ get_account_balance() and get_trade_volume()

### ISSUE THREAD

**Issue by 4bluegen2s** [dominiktraxl/pykrakenapi#61]
```
api = krakenex.API()
api.load_key(KeyPath)
k   = KrakenAPI(api)

Balance = k.get_account_balance()
TradeVol = k.get_trade_volume()
```

Both functions are returning:
    **KrakenAPIError: ['EAPI:Invalid nonce']**

Other functions like **get_tradable_asset_pairs()** and **get_ohlc_data('XBTUSD')** are working just fine.

As far as I know, get_account_balance() worked for me a few days ago.

Thank you for the help

**Comment by dominiktraxl** [comment]
I can't reproduce the error, it's working for me. Are you still getting the same error?

**Comment by lasmeter** [comment]
k.add_standard_order(pair="ATOMXBT", type="buy", ordertype="limit", volume="420.0", price="0.00042", validate=False)

 1982         # query
-> 1983         res = self.api.query_private('AddOrder', data=data)

add_standard_order is not ring

**Comment by Mathiaszero** [comment]
`from time import sleep
import krakenex
from pykrakenapi import KrakenAPI
api=krakenex.API()
kraken=KrakenAPI(api)

api.load_key('Documents\KrakenPass.txt')
bal=kraken.get_account_balance()`

I am also getting the same error. I also tested everything before 'bal=' and there were no issues showing. Nonce and then call rate limiter exceeded.

**Comment by jculbert** [comment]
I had the same problem when I was using a key that had been used by another application. Using a newly created key got it working.
