### ISSUE TITLE
average market price for a given volume

### ISSUE THREAD

**Issue by jonnymaserati** [dominiktraxl/pykrakenapi#66]
I find it a bit weird that there's no call to return the current market price (average price) for a volume trade (at least I can't find anything) in the API, so I've written one for a class I'm writing. I'm happy to pass this on if you want to modify it to fit into your code, else I can create a branch and insert it via an pull request?

Maybe this is out of scope for an API wrapper, but let me know...

**Comment by dominiktraxl** [comment]
Hi @jonnymaserati,
Thank you for the offer, but I'd like to keep this as simple as possible with a 1-to-1 correspondence to the original Kraken API.

**Comment by jonnymaserati** [comment]
Completely understand @dominiktraxl!
