### ISSUE TITLE
Lib doesn't handle properly a request for which the result dataframe is empty

### ISSUE THREAD

**Issue by jsgonsette** [dominiktraxl/pykrakenapi#7]
Just an example that made me notice the problem: I tried to get all the withdrawal entries from the ledger of my account. But there is no such entry. The lib crashes by trying to access some attribute of the dataframe that doesn't exist. It would be nice if the lib just return None in this case. 
 
I guess the problem is the same for all the requests.

**Comment by dominiktraxl** [comment]
Thanks, I changed the code such that empty dataframes aren't processed any more.
