### ISSUE TITLE
Remove "UNTESTED" comment

### ISSUE THREAD

**Issue by jonnymaserati** [dominiktraxl/pykrakenapi#70]
I've tested this pretty thoroughly and it looks to be working just fine! :-) I suggest that this comment be removed for the next release.

https://github.com/dominiktraxl/pykrakenapi/blob/8a1aef6388d39f146a9e491a9a55e9db35664cca/pykrakenapi/pykrakenapi.py#L2397

**Comment by dominiktraxl** [comment]
Thanks for the comment, it will be removed on the next release.
