### ISSUE TITLE
['EGeneral:Invalid arguments:timeinforce'] when calling add_standard_order()

### ISSUE THREAD

**Issue by FredHaa** [dominiktraxl/pykrakenapi#75]
When I call add_standard_order() I get the following argument error for `timeinforce`:

```
  File "/home/frederik/.local/lib/python3.9/site-packages/pykrakenapi/pykrakenapi.py", line 2411, in add_standard_order
    raise KrakenAPIError(res['error'])
pykrakenapi.pykrakenapi.KrakenAPIError: ['EGeneral:Invalid arguments:timeinforce']
```

I get the same error for all (`["GTC", "IOC", "GTD"]`) legal values described in the docs.
The `trigger` parameter also gives errors.

It can be temporarily fixed by setting both parameters to `None`, but it should be fixed in the API.

```
pykrakenapi.add_standard_order(ordertype, type, self.pair, volume=volume, validate=False, timeinforce=None, trigger=None)
```

**Comment by jdslomka** [comment]
I also have an issue with the `trigger` parameter. It seems validating the api call returns `['EGeneral:Invalid arguments:trigger']`

**Comment by lorisleitner** [comment]
Same problem, please fix

**Comment by dominiktraxl** [comment]
I have taken those arguments directly from the official Kraken API, so I am a bit surprised they do not work. Anyway, I have just changed the defaults of `trigger` and `timeinforce` to None, so it should work with the default parameters now.

**Comment by jonnymaserati** [comment]
Don’t be surprised, there are plenty of issues with the Kraken API! 😬
